#!/bin/sh
# RALLY — build the ISOLATED PREVIEW from the app source.
#
#   sh rally/tools/build-preview.sh <src rally dir> <out dir> [preview id]
#
# Copies the app (never its tests, database artifacts or tools) and rewrites
# exactly the files that keep the copy apart from production on a shared
# origin. The MapKit token is read from the environment variable
# MAPKIT_TOKEN, written into the OUTPUT's js/mapkit-config.js, and never
# printed, never logged, never written anywhere else. With MAPKIT_TOKEN
# unset the preview still builds and simply draws the offline-capable map.
#
# What the build changes, and why (each is verified at the end):
#   js/preview-config.js   RALLY_PREVIEW = { db, cache, isolated, demo, label }
#   js/cloud-config.js     url and anonKey emptied — no team server, ever
#   sw.js                  CACHE / TILE_CACHE / FAMILY moved to their own family
#   manifest.webmanifest   its own name, so the home-screen icon says PREVIEW
#   index.html             its own <title>
#   js/mapkit-config.js    the token from MAPKIT_TOKEN (output only)
set -eu
SRC="${1:?source rally dir}"
OUT="${2:?output dir}"
ID="${3:-p5}"
DB="rally-preview-$ID"
# everything the id names is derived from it: two previews on one origin
# must not share a cache family any more than a database
FAMILY="rally${ID}-"
SHORT="RALLY $(printf '%s' "$ID" | tr '[:lower:]' '[:upper:]')"

[ -f "$SRC/index.html" ] && [ -f "$SRC/sw.js" ] || { echo "not a rally dir: $SRC" >&2; exit 2; }
rm -rf "$OUT"; mkdir -p "$OUT"
# the app, without the parts that are not the app
( cd "$SRC" && tar --exclude=./tests --exclude=./db --exclude=./tools --exclude='./*.md' -cf - . ) | ( cd "$OUT" && tar -xf - )

BUILD="$(sed -n 's/.*window\.RALLY_BUILD *= *"\(v[0-9]*\)".*/\1/p' "$OUT/index.html" | head -1)"
[ -n "$BUILD" ] || { echo "no RALLY_BUILD in index.html" >&2; exit 2; }
VN="${BUILD#v}"

# 1. the preview switch every module reads
cat > "$OUT/js/preview-config.js" <<CFG
/* RALLY — ISOLATED PREVIEW build (generated by tools/build-preview.sh).
   Not RALLY production. Its own database, its own caches, no team server. */
window.RALLY_PREVIEW = {
  id: "$ID",
  db: "$DB",
  cache: "$FAMILY",
  isolated: true,
  demo: true,
  label: "PREVIEW $BUILD",
};
CFG

# 2. no cloud, by configuration as well as by the code guard
cat > "$OUT/js/cloud-config.js" <<CFG
/* RALLY — ISOLATED PREVIEW: no cloud project. Both fields are empty on
   purpose, and js/cloud.js refuses every call regardless when
   RALLY_PREVIEW.isolated is set. */
window.RALLY_CLOUD = window.RALLY_CLOUD || { url: "", anonKey: "" };
CFG

# 3. the service worker's own cache family
sed -i.bak \
  -e "s/^const CACHE = \"rally-v$VN\";/const CACHE = \"${FAMILY}v$VN\";/" \
  -e "s/^const TILE_CACHE = \"rally-tiles-v1\";/const TILE_CACHE = \"${FAMILY}tiles-v1\";/" \
  -e "s/^const FAMILY = \"rally-\";/const FAMILY = \"$FAMILY\";/" "$OUT/sw.js"
rm -f "$OUT/sw.js.bak"

# 4. the home-screen name and the tab title
sed -i.bak \
  -e 's/"name": "RALLY — Door-to-Door Sales"/"name": "RALLY PREVIEW — isolated test build"/' \
  -e "s/\"short_name\": \"RALLY\"/\"short_name\": \"$SHORT\"/" "$OUT/manifest.webmanifest"
rm -f "$OUT/manifest.webmanifest.bak"
sed -i.bak -e 's#<title>[^<]*</title>#<title>RALLY PREVIEW (isolated)</title>#' "$OUT/index.html"
rm -f "$OUT/index.html.bak"

# 5. the token — output only, from the environment, never echoed
if [ -n "${MAPKIT_TOKEN:-}" ]; then
  # printf %s through a heredoc-free path: the value never appears on a
  # command line (ps) and never in this script's output (set -u, no echo)
  { printf '%s\n' '/* RALLY — Apple MapKit token for the ISOLATED PREVIEW on its authorized origin. Generated at publish time; never in git. */'
    printf 'window.RALLY_MAPKIT = { token: "%s" };\n' "$MAPKIT_TOKEN"; } > "$OUT/js/mapkit-config.js"
  TOKEN_STATE="stamped"
else
  TOKEN_STATE="absent (offline-capable map only)"
fi

# 6. verify — every rewrite is checked, and nothing about the token is shown
ok=1
grep -q "db: \"$DB\"" "$OUT/js/preview-config.js" || { echo "preview-config not stamped" >&2; ok=0; }
grep -q 'isolated: true' "$OUT/js/preview-config.js" || { echo "preview-config not isolated" >&2; ok=0; }
grep -q 'url: ""' "$OUT/js/cloud-config.js" || { echo "cloud-config not emptied" >&2; ok=0; }
grep -q "^const CACHE = \"${FAMILY}v$VN\";" "$OUT/sw.js" || { echo "sw CACHE not moved" >&2; ok=0; }
grep -q "^const TILE_CACHE = \"${FAMILY}tiles-v1\";" "$OUT/sw.js" || { echo "sw TILE_CACHE not moved" >&2; ok=0; }
grep -q "^const FAMILY = \"$FAMILY\";" "$OUT/sw.js" || { echo "sw FAMILY not moved" >&2; ok=0; }
grep -q 'rally-v' "$OUT/sw.js" && { echo "sw still names a production cache" >&2; ok=0; }
grep -q 'RALLY PREVIEW' "$OUT/manifest.webmanifest" || { echo "manifest not renamed" >&2; ok=0; }
grep -q 'RALLY PREVIEW' "$OUT/index.html" || { echo "title not renamed" >&2; ok=0; }
[ ! -e "$OUT/tests" ] && [ ! -e "$OUT/db" ] && [ ! -e "$OUT/tools" ] || { echo "non-app files copied" >&2; ok=0; }
grep -q 'supabase' "$OUT/js/cloud-config.js" && { echo "cloud-config still names a project" >&2; ok=0; }
[ "$ok" = 1 ] || exit 1
echo "preview built: $OUT · build $BUILD · db $DB · caches ${FAMILY}* · cloud off · token $TOKEN_STATE"
