#!/bin/sh
# Generate db/test/verify-production.editor.sql — the Supabase SQL Editor form
# of verify-production.sql — from the psql file, so the two cannot drift.
#
# Why a second form exists: the editor rejects the psql-only "\set" line, and
# it shows only the LAST statement's result, which in the psql file is the
# ROLLBACK. The editor form runs the VERBATIM probes inside one PL/pgSQL
# subtransaction that is always rolled back (a deliberate exception at the
# end) and returns the results from the final SELECT. Nothing is kept.
#
#   sh db/test/build-editor-verify.sh          # regenerate
#   sh db/test/build-editor-verify.sh --check  # fail if the committed copy is stale
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/verify-production.editor.sql"
TMP="$(mktemp)"
python3 - "$DIR/verify-production.sql" "$TMP" <<'PY'
import sys
src = open(sys.argv[1]).read().split("\n")
a = next(i for i, l in enumerate(src) if l.startswith("  select p.id, p.team_id into rep_id, team"))
b = next(i for i, l in enumerate(src) if l.startswith("end $$;"))
body = "\n".join(src[a:b])
assert body.count("insert into probe_result values (") >= 20
body = body.replace("insert into probe_result values (", "res := res || pg_temp.v39_row(")
assert body.count("    return;") == 1
body = body.replace("    return;", "    raise exception using message = 'v39-probe-rollback';")
assert "probe_result" not in body
out = """-- RALLY v39 — POST-MIGRATION BEHAVIOURAL VERIFICATION (Supabase SQL Editor form).
-- GENERATED by db/test/build-editor-verify.sh from verify-production.sql — edit that.
--
-- The probes below are the VERBATIM probes of db/test/verify-production.sql.
-- Two things differ, both for the SQL Editor:
--   * the psql-only "\\set ON_ERROR_STOP on" line is gone;
--   * the editor shows only the LAST statement's result, so instead of
--     "begin … select … rollback", the probes run inside ONE PL/pgSQL
--     subtransaction that is always rolled back (a deliberate exception at
--     the end), and the results are returned by the final SELECT.
-- NOTHING is kept: every territory, pin, customer, split and doorbell
-- message the probes create is undone before the results are returned.
-- Production rows are only ever READ (probe 12 counts them).
-- It picks a real rep and a real leader/manager/owner off your own team.

create or replace function pg_temp.v39_row(step text, ok boolean, detail text)
returns jsonb language sql immutable as $f$
  select jsonb_build_array(jsonb_build_object('step', step, 'ok', ok, 'detail', detail))
$f$;

create or replace function pg_temp.v39_verify()
returns table(step text, result text, detail text) language plpgsql as $$
declare
  rep_id uuid; boss_id uuid; team uuid; tid text; tid2 text; cid text; n int; ok boolean;
  stored jsonb; res jsonb := '[]'::jsonb;
begin
  begin
""" + body + """
    -- every write above is undone here; the results live in `res`
    raise exception using message = 'v39-probe-rollback';
  exception when others then
    if sqlerrm <> 'v39-probe-rollback' then
      res := res || pg_temp.v39_row('UNEXPECTED ERROR', false, sqlerrm);
    end if;
  end;
  begin execute 'reset role'; exception when others then null; end;
  perform set_config('request.jwt.claims', '', true);
  return query
    select r->>'step',
           case when (r->>'ok')::boolean then 'PASS' else '*** FAIL ***' end,
           r->>'detail'
      from jsonb_array_elements(res) r
     order by case when r->>'step' = 'SETUP' then 0
                   when r->>'step' ~ '^[0-9]+' then (regexp_match(r->>'step', '^[0-9]+'))[1]::int
                   else 99 end;
end $$;

select * from pg_temp.v39_verify();
"""
open(sys.argv[2], "w").write(out)
PY
if [ "$1" = "--check" ]; then
  if cmp -s "$TMP" "$OUT"; then echo "EDITOR VERIFY: in sync with verify-production.sql"; rm -f "$TMP"; exit 0; fi
  echo "EDITOR VERIFY: STALE — run sh db/test/build-editor-verify.sh"; rm -f "$TMP"; exit 1
fi
mv "$TMP" "$OUT"; echo "regenerated $OUT"
