-- RALLY v39 — POST-MIGRATION BEHAVIOURAL VERIFICATION (Supabase SQL Editor form).
-- GENERATED by db/test/build-editor-verify.sh from verify-production.sql — edit that.
--
-- The probes below are the VERBATIM probes of db/test/verify-production.sql.
-- Two things differ, both for the SQL Editor:
--   * the psql-only "\set ON_ERROR_STOP on" line is gone;
--   * the editor shows only the LAST statement's result, so instead of
--     "begin … select … rollback", the probes run inside ONE PL/pgSQL
--     subtransaction that is always rolled back (a deliberate exception at
--     the end), and the results are returned by the final SELECT.
-- NOTHING is kept: every territory, pin, customer, split and doorbell
-- message the probes create is undone before the results are returned.
-- Production rows are only ever READ (probe 12 counts them).
-- It picks a real rep and a real leader/manager/owner off your own team.

create or replace function pg_temp.v39_row(step text, ok boolean, detail text)
returns jsonb language sql immutable as $f$
  select jsonb_build_array(jsonb_build_object('step', step, 'ok', ok, 'detail', detail))
$f$;

create or replace function pg_temp.v39_verify()
returns table(step text, result text, detail text) language plpgsql as $$
declare
  rep_id uuid; boss_id uuid; team uuid; tid text; tid2 text; cid text; n int; ok boolean;
  stored jsonb; res jsonb := '[]'::jsonb;
begin
  begin
  select p.id, p.team_id into rep_id, team from public.profiles p
    where p.role = 'rep' and p.team_id is not null and not p.disabled limit 1;
  select p.id into boss_id from public.profiles p
    where p.role in ('leader','manager','owner') and p.team_id = team
      and not p.disabled limit 1;
  if rep_id is null or boss_id is null then
    res := res || pg_temp.v39_row('SETUP', false,
      'need one enabled rep AND one enabled leader/manager/owner on the same team');
    raise exception using message = 'v39-probe-rollback';
  end if;
  res := res || pg_temp.v39_row('SETUP', true,
    'team ' || team || ' — probing as a real rep and a real leader');

  tid := 'v39-probe-' || substr(md5(random()::text), 1, 10);
  tid2 := 'v39-probe-b-' || substr(md5(random()::text), 1, 10);
  cid := 'v39-probe-c-' || substr(md5(random()::text), 1, 10);

  -- 1. a rep may NOT create a territory
  perform set_config('request.jwt.claims', json_build_object('sub', rep_id)::text, true);
  execute 'set local role authenticated';
  begin
    insert into public.territories (team_id, id, name) values (team, tid, 'probe');
    res := res || pg_temp.v39_row('1 rep territory insert', false, 'ALLOWED — 0003 is not in effect');
  exception when insufficient_privilege then
    res := res || pg_temp.v39_row('1 rep territory insert', true, 'denied, as required');
  end;

  -- 2. a rep MAY still write their own work
  begin
    insert into public.pins (team_id, id, lat, lng) values (team, 'v39-probe-pin', 1, 1);
    insert into public.customers (team_id, id, first, last) values (team, cid, 'Probe', 'Row');
    res := res || pg_temp.v39_row('2 rep pin + customer write', true, 'allowed, as required');
  exception when others then
    res := res || pg_temp.v39_row('2 rep pin + customer write', false, 'DENIED — reps cannot work: ' || sqlerrm);
  end;

  -- 3. an older-client UPSERT cannot erase an existing autopay request
  update public.customers set data =
    '{"payment":{"method":"ach","autopayRequested":true,"status":"pending_setup"}}'::jsonb
    where team_id = team and id = cid;
  insert into public.customers (team_id, id, first, last, data)
    values (team, cid, 'Probe', 'Row', '{"payment":{"method":"ach","autopay":true}}'::jsonb)
    on conflict (team_id, id) do update set data = excluded.data;
  select c.data->'payment' into stored from public.customers c where c.team_id = team and c.id = cid;
  ok := stored->>'autopayRequested' = 'true' and stored->>'status' = 'pending_setup';
  res := res || pg_temp.v39_row('3 old-client upsert preserves the request', ok, stored::text);

  -- 4. no client can make a payment method look live
  insert into public.customers (team_id, id, first, last, data)
    values (team, cid, 'Probe', 'Row',
      '{"payment":{"method":"card","autopayRequested":true,"status":"active"}}'::jsonb)
    on conflict (team_id, id) do update set data = excluded.data;
  select c.data->'payment' into stored from public.customers c where c.team_id = team and c.id = cid;
  ok := coalesce(stored->>'status','') <> 'active';
  res := res || pg_temp.v39_row('4 status "active" cannot be claimed', ok, stored::text);

  -- 5. a credential cannot be smuggled through an allowed field
  insert into public.customers (team_id, id, first, last, data)
    values (team, cid, 'Probe', 'Row',
      '{"payment":{"method":"4111111111111111","last4":"4111111111111111",
        "card":{"number":"4111111111111111"},
        "billingAddress":{"street":"4111111111111111","city":"Provo","state":"UT","zip":"84604"}}}'::jsonb)
    on conflict (team_id, id) do update set data = excluded.data;
  select c.data->'payment' into stored from public.customers c where c.team_id = team and c.id = cid;
  ok := position('4111111111111111' in stored::text) = 0
        and not (stored ? 'card') and not (stored ? 'ach');
  res := res || pg_temp.v39_row('5 credentials cannot ride an allowed field', ok, stored::text);

  reset role;
  perform set_config('request.jwt.claims', '', true);

  -- 6. a leader/manager/owner CAN do territory work
  perform set_config('request.jwt.claims', json_build_object('sub', boss_id)::text, true);
  execute 'set local role authenticated';
  begin
    -- its OWN id, so this probe can never fail because an earlier one
    -- (wrongly) succeeded
    insert into public.territories (team_id, id, name) values (team, tid2, 'probe');
    update public.territories set name = 'probe renamed' where team_id = team and id = tid2;
    get diagnostics n = row_count;
    res := res || pg_temp.v39_row('6 leadership territory insert + update', n = 1,
      n || ' row(s) updated');
  exception when others then
    res := res || pg_temp.v39_row('6 leadership territory insert + update', false,
      'DENIED — leadership cannot manage territories: ' || sqlerrm);
  end;
  reset role;
  perform set_config('request.jwt.claims', '', true);

  -- 7. a rep may NOT reach the Smart Split function
  perform set_config('request.jwt.claims', json_build_object('sub', rep_id)::text, true);
  execute 'set local role authenticated';
  begin
    perform public.smart_split_territory(tid2, 'probe-op-rep',
      jsonb_build_array(
        jsonb_build_object('id', tid2 || '-a', 'name', 'a',
          'polygon', '[[0,0],[1,0],[1,1]]'::jsonb),
        jsonb_build_object('id', tid2 || '-b', 'name', 'b',
          'polygon', '[[1,0],[2,0],[2,1]]'::jsonb)));
    res := res || pg_temp.v39_row('7 rep smart split', false,
      'ALLOWED — a rep split a territory');
  exception when others then
    res := res || pg_temp.v39_row('7 rep smart split', true,
      'refused: ' || sqlerrm);
  end;
  reset role;
  perform set_config('request.jwt.claims', '', true);

  -- 8. a leader CAN, it is atomic, and repeating it creates nothing new
  perform set_config('request.jwt.claims', json_build_object('sub', boss_id)::text, true);
  execute 'set local role authenticated';
  begin
    perform public.smart_split_territory(tid2, 'probe-op-boss',
      jsonb_build_array(
        jsonb_build_object('id', tid2 || '-a', 'name', 'a',
          'polygon', '[[0,0],[1,0],[1,1]]'::jsonb),
        jsonb_build_object('id', tid2 || '-b', 'name', 'b',
          'polygon', '[[1,0],[2,0],[2,1]]'::jsonb)));
    select count(*) into n from public.territories
      where team_id = team and id in (tid2 || '-a', tid2 || '-b') and deleted_at is null;
    select (deleted_at is not null) into ok from public.territories
      where team_id = team and id = tid2;
    res := res || pg_temp.v39_row('8 leadership smart split is atomic',
      n = 2 and ok, n || ' child(ren), parent retired = ' || ok);
    -- the same operation again: recognised, never repeated
    perform public.smart_split_territory(tid2, 'probe-op-boss',
      jsonb_build_array(
        jsonb_build_object('id', tid2 || '-a', 'name', 'a',
          'polygon', '[[0,0],[1,0],[1,1]]'::jsonb),
        jsonb_build_object('id', tid2 || '-b', 'name', 'b',
          'polygon', '[[1,0],[2,0],[2,1]]'::jsonb)));
    select count(*) into n from public.territories
      where team_id = team and id like tid2 || '-%' and deleted_at is null;
    res := res || pg_temp.v39_row('9 smart split retry creates nothing new',
      n = 2, n || ' child(ren) after the retry');
  exception when others then
    res := res || pg_temp.v39_row('8 leadership smart split is atomic', false,
      'FAILED: ' || sqlerrm);
  end;
  reset role;
  perform set_config('request.jwt.claims', '', true);

  -- 10. the FINAL 0004: a payment-less production upsert keeps the whole object
  perform set_config('request.jwt.claims', json_build_object('sub', rep_id)::text, true);
  execute 'set local role authenticated';
  begin
    insert into public.customers (team_id, id, first, last, email, phones, created_by, deleted_at, data)
    values (team, cid || '-w', 'probe', '', '', '[]'::jsonb, rep_id, null,
      '{"payment":{"method":"ach","autopayRequested":true,"status":"pending_setup","card":{"name":"Probe Name"}}}'::jsonb);
    insert into public.customers (team_id, id, first, last, email, phones, created_by, deleted_at, data)
    values (team, cid || '-w', 'probe', '', '', '[]'::jsonb, rep_id, null,
      '{"notesForever":"payment-less write"}'::jsonb)
    on conflict (team_id, id) do update set
      team_id = excluded.team_id, id = excluded.id, first = excluded.first, last = excluded.last,
      email = excluded.email, phones = excluded.phones, created_by = excluded.created_by,
      deleted_at = excluded.deleted_at, data = excluded.data;
    select data->'payment' into stored from public.customers where team_id = team and id = cid || '-w';
    res := res || pg_temp.v39_row('10 payment-less upsert keeps the object',
      stored->>'autopayRequested' = 'true' and stored->'card'->>'name' = 'Probe Name',
      coalesce(stored::text, '<<ABSENT>>'));
  exception when others then
    res := res || pg_temp.v39_row('10 payment-less upsert keeps the object', false, 'ERROR: ' || sqlerrm);
  end;
  -- 11. …and a tombstone carries nothing
  begin
    update public.customers set deleted_at = now(), data = '{}'::jsonb, first = '', last = '', email = '', phones = '[]'::jsonb
     where team_id = team and id = cid || '-w';
    select data into stored from public.customers where team_id = team and id = cid || '-w';
    res := res || pg_temp.v39_row('11 a tombstone carries no payment',
      not (stored ? 'payment'), stored::text);
  exception when others then
    res := res || pg_temp.v39_row('11 a tombstone carries no payment', false, 'ERROR: ' || sqlerrm);
  end;
  reset role;
  perform set_config('request.jwt.claims', '', true);

  -- 12. the 0006 STATE: what the table HOLDS obeys the rule, every row, every team
  select count(*) into n from public.customers
   where data::text ~ '"(number|cardNumber|exp|expiry|cvv|cvc|routing|account|accountNumber|routingNumber)"'
      or (data->'payment' ? 'last4' and data->'payment'->>'last4' !~ '^[0-9]{4}$')
      or (data->'payment' ? 'autopay')
      or (deleted_at is not null and data ? 'payment')
      or (jsonb_typeof(data->'payment') is not null and jsonb_typeof(data->'payment') <> 'object');
  res := res || pg_temp.v39_row('12 every stored row obeys the final rule (0006 ran)',
    n = 0, n || ' row(s) violate it — 0006 has not run, or something wrote past the trigger');
    -- every write above is undone here; the results live in `res`
    raise exception using message = 'v39-probe-rollback';
  exception when others then
    if sqlerrm <> 'v39-probe-rollback' then
      res := res || pg_temp.v39_row('UNEXPECTED ERROR', false, sqlerrm);
    end if;
  end;
  begin execute 'reset role'; exception when others then null; end;
  perform set_config('request.jwt.claims', '', true);
  return query
    select r->>'step',
           case when (r->>'ok')::boolean then 'PASS' else '*** FAIL ***' end,
           r->>'detail'
      from jsonb_array_elements(res) r
     order by case when r->>'step' = 'SETUP' then 0
                   when r->>'step' ~ '^[0-9]+' then (regexp_match(r->>'step', '^[0-9]+'))[1]::int
                   else 99 end;
end $$;

select * from pg_temp.v39_verify();
